# Generated by Django 3.0.5 on 2020-12-21 10:53
import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201221_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('join_date', models.DateField(default=datetime.date.today)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
