# Generated by Django 3.0.5 on 2020-12-26 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201226_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.CharField(max_length=100, verbose_name='Design Name')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='img')),
                ('status', models.BooleanField(default=True)),
                ('inserted_by', models.PositiveIntegerField(choices=[(1, 'Admin'), (2, 'Designer')], default=1)),
                ('creator_id', models.IntegerField(verbose_name='Creator Name')),
                ('created_at', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
