# Generated by Django 3.0.5 on 2021-02-08 14:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210118_2303'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='design',
        #     name='price',
        #     field=models.IntegerField(default=0),
        #     preserve_default=False,
        # ),
        # migrations.AlterField(
        #     model_name='designer',
        #     name='phone',
        #     field=models.CharField(max_length=12),
        # ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('datetime', models.DateField(default=datetime.date.today)),
                ('sender', models.IntegerField(verbose_name=2)),
                ('type', models.IntegerField(verbose_name=2)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Designer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
    ]
